FOR_SM = [
"bobby pins",
"breath strip pack",
"clear nail polish",
"clipboard",
"Clorox to go packets",
"clothespins",
"contact lens case",
"cough drops - Halls, sugar free, triple soothing action, black cherry",
"first aid kit (mini) with aspirin and advil",
"fray check bottle",
"gum pack",
"hair comb",
"hair ties ",
"hand sanitizer, travel size",
"Home and travel sewing kit",
"hot/cold pack for injuries",
"makeup remover pads",
"medical tape",
"mini composition book",
"moleskin sheet",
"nail clippers",
"nail file",
"odorless lotion, travel size",
"pads ",
"pencil sharpener, hand-held",
"pencils for actors to steal",
"short black gel pens",
"small bag of tiny hair rubberbands",
"small washcloth",
"snack bars",
"sticker label sheets (2)",
"tampons",
"tea packets",
"Tide To Go pen",
"tissue packet",
"tweezers",
"Tylenol cold pills"
]

FOR_CREW = [
"A clip",
"aux cable",
"bit set with screwdriver",
"black gaff tape roll",
"c-wrench with rubber handle",
"caribeaners",
"coffee (folgers packets)",
"cuts of tie line",
"D batteries",
"drawing pencil (graphite stick pen)",
"electrical tape roll (black)",
"flash drive ",
"floppy disc - for older EOS light boards",
"gamchek",
"gels - (size of cuts) and (blue, red, diffusion)",
"glo tape roll",
"grease pen",
"grounded Edison extension",
"keychain laser pointer",
"lighter",
"paper tape roll",
"silver sharpie pen",
"small calculator",
"small level",
"spike tape rolls",
"stress ball that can be used as preliminary prop",
"tape measure - 16 ft.",
"tape roll",
"tea (2x 3 different options)",
"thick blue sharpie",
"utility knife",
"zip ties"
]

FOR_CREW = [
"1-hole puncher",
"AA batteries",
"AAA batteries",
"academic planner, undated",
"binder clips",
"binder clips",
"binder reinforcement labels/stickers",
"black binder 0.5 in",
"black thin sharpie",
"blank cards & envelopes (for thank you notes)",
"busienss card holder  (engraved for customer)",
"canvas reusable bag",
"CD, blank, and case",
"color paper assortment",
"cube tap (Edison)",
"Duracel flashlight with batteries. Has 3 settings",
"earphones",
"eraseable highlighters ",
"eraseable pens",
"erasers",
"glue stick",
"laptop USB LED light for tech",
"large binder clip",
"mechanical pencils",
"mini hilighters",
"mini stapler",
"multitool",
"neon spike tape - either yellow, green, or orange",
"pair small scissors",
"paperclips",
"pen assortment",
"pen bag",
"pencil refill",
"pink hilighter",
"Post-its (various)",
"regular size envelopes",
"ruler",
"sandwich (ziploc style) bags, clear",
"security envelopes",
"staple refills",
"subtle spike tape - either dark blue or tan",
"techgear Mega Filled Binder",
"Thank You cards",
"USB to wall charger input (American)",
"voyager tool bag - 15"",
"water bottle - (bodium or Kleen canteen?)",
"white binder 1.5 in",
"white printer paper",
"whiteout tape roll",
"wine & bottle opener",
"yellow hilighter",
"yellow lined paper pad"
]



