# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73876664a31a3486f40f5aa66f4b064dabcbf0e72232d61d966a88fefcb96adfa759a91c43ea62d23c6d9f1662f5da42cf5cda1eaecdce77dad25c1833e37f42

test:
  secret_key_base: 6e2621b6a9a0b77f2d8cbc5c467368b80b28148489477413813e0ed0adff43404e9c6762280ed10485594d5a2116bbd5f21db55ad89603c2b227c008201176de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
